version: '3' 
services: 

  image-service:
    container_name: photo-gallery-image-service
    image: photo-gallery-image-service
    restart: always
    environment:
      SERVER_PORT: ${SERVER_PORT}
      MONGODB_HOST: ${MONGODB_HOST}
      MONGODB_PORT: ${MONGODB_PORT}
      DEFAULT_USER: ${DEFAULT_USER}
      DEFAULT_PASSWORD: ${DEFAULT_PASSWORD}
      DEFAULT_DB: ${DEFAULT_DB}
    networks: 
      - photo-gallery-net
  
  post-service:
    container_name: photo-gallery-post-service
    image: photo-gallery-post-service
    restart: always
    environment:
      SERVER_PORT: ${SERVER_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DEFAULT_USER: ${DEFAULT_USER}
      DEFAULT_PASSWORD: ${DEFAULT_PASSWORD}
      DEFAULT_DB: ${DEFAULT_DB}
    networks: 
      - photo-gallery-net

networks:
  photo-gallery-net:
    external:
      name: infra_photo-gallery-net